"""
Manual ReAct agent loop. No framework — no LangChain agent executor, no
ReAct library. The loop itself (deciding what to do next, executing a
tool, feeding the result back as an observation, deciding whether to stop)
is hand-written here in plain Python.

Loop shape, matching the ReAct paper's own framing:

    Thought:      model reasons about what it needs to do next
    Action:       model picks a tool (search_facts / calculate) and an input,
                  OR picks final_answer to stop
    Observation:  the TOOL's result (not generated by the model) is fed
                  back into the next prompt
    ... repeats until final_answer or MAX_ITERATIONS is hit ...

This also matches the Agent Loop framing from the Week 1 doc:
    Perceive  = the model reads the running transcript (question + all
                prior thought/action/observation steps) at the top of
                every call
    Plan      = the `thought` field
    Act       = the `action` + `action_input` fields, executed by
                run_tool() — NOT by the model itself
    Observe   = the tool's return value, appended to the transcript
                before the next call
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field

from dotenv import load_dotenv
from groq import BadRequestError, Groq

from models import AgentStep
from tools import calculate, search_facts

MODEL = "openai/gpt-oss-120b"

# A hard ceiling on loop iterations. Without this, a model that never
# emits "final_answer" (e.g. due to a confusing question, or just model
# unreliability) would loop forever, silently burning API quota. This is
# the agent-loop equivalent of the circuit breaker built in Project 1-P-C
# for rate-limit pacing — same principle (fail loud and bounded, don't
# hang), different failure mode being guarded against.
MAX_ITERATIONS = 6

SYSTEM_PROMPT = """You are a ReAct-style reasoning agent. You have access to exactly two tools:

1. search_facts — searches a small fact database. Use this for factual/knowledge questions.
2. calculate — evaluates a math expression using Python's eval(). Use this for arithmetic.

For every step, think about what you need to do next, then choose ONE action:
- "search_facts" with the search query as action_input
- "calculate" with the math expression as action_input
- "final_answer" with your complete answer to the user as action_input, once you have enough information

Only choose final_answer when you have actually gathered the information needed (via a tool call) or the question needs no tool at all. Do not guess at facts you could look up — use search_facts instead.

IMPORTANT: Respond ONLY with the JSON object matching the required schema (thought, action, action_input fields). Do NOT use any native function-calling or tool-calling mechanism — there is no tools parameter in this request, and attempting to call a function directly (rather than describing it in the action/action_input fields) will cause an error. Always respond with plain JSON matching the schema, never with a function call.
"""


@dataclass
class AgentTranscript:
    """Tracks the full Thought/Action/Observation history for one run, so
    each new model call can "perceive" everything that happened before."""

    question: str
    steps: list[tuple[AgentStep, str | None]] = field(default_factory=list)
    # each entry: (the model's AgentStep, the resulting observation text —
    # None only for the final final_answer step, which has no observation)

    def render_for_prompt(self) -> str:
        lines = [f"User's question: {self.question}"]
        for step, observation in self.steps:
            lines.append(f"Thought: {step.thought}")
            lines.append(f"Action: {step.action}[{step.action_input}]")
            if observation is not None:
                lines.append(f"Observation: {observation}")
        return "\n".join(lines)


def get_client() -> Groq:
    load_dotenv()
    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        raise RuntimeError(
            "GROQ_API_KEY not set. Create a .env file with GROQ_API_KEY=gsk_... "
            "or set it as an environment variable."
        )
    return Groq(api_key=api_key, timeout=30.0)


def run_tool(action: str, action_input: str) -> str:
    """Executes the chosen tool. This is the 'Act' step — note that the
    MODEL never runs the tool itself, it only decides which one to call
    and with what input. The actual execution (including the eval() call
    inside calculate()) happens here, in plain Python, outside the model's
    control. That separation is the entire point of tool-calling: the
    model can request an action, but the code decides whether and how to
    actually perform it."""
    if action == "search_facts":
        return search_facts(action_input)
    elif action == "calculate":
        return calculate(action_input)
    else:
        raise ValueError(f"run_tool() should never be called with action={action!r}")


def get_next_step(client: Groq, transcript: AgentTranscript, temperature: float = 0.2) -> AgentStep:
    """One LLM call: given the transcript so far, decide the next
    Thought + Action (or final_answer).

    Known model quirk (confirmed live, and documented by Groq itself):
    openai/gpt-oss-120b can sometimes drift into emitting a NATIVE tool
    call (the {"name": ..., "arguments": ...} function-calling format)
    even though no `tools` parameter is given in this request at all —
    Groq's API then rejects it with 'Tool choice is none, but model
    called a tool' (400 Bad Request). This isn't caused by a bug in our
    schema or prompt structure; Groq's own docs confirm this varies by
    model and that retrying at a lower temperature is the recommended
    mitigation (https://console.groq.com/docs/tool-use/local-tool-calling).
    Vaguer, more open-ended questions seem to trigger it more than crisp
    single-domain ones — observed live on a "what's the relationship
    between X and Y" style question, not on direct math/fact questions.
    """
    schema = AgentStep.model_json_schema()
    try:
        response = client.chat.completions.create(
            model=MODEL,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": transcript.render_for_prompt()},
            ],
            response_format={
                "type": "json_schema",
                "json_schema": {"name": "agent_step", "strict": True, "schema": schema},
            },
            # Was 400 — too tight. gpt-oss models spend tokens on internal
            # reasoning before emitting visible content (confirmed
            # extensively in Project 1-P-C, where similar truncation at a
            # too-low cap caused near-identical "max completion tokens
            # reached before generating a valid document" failures).
            # AgentStep's JSON itself is small (3 short fields), but the
            # reasoning overhead needs real headroom regardless.
            max_completion_tokens=900,
            temperature=temperature,
        )
    except BadRequestError as e:
        body = getattr(e, "body", None) or {}
        message = (body.get("error", {}) if isinstance(body, dict) else {}).get("message", "")
        failed_generation = (
            body.get("error", {}).get("failed_generation", "")
            if isinstance(body, dict)
            else ""
        )

        if "Tool choice is none, but model called a tool" in message:
            if temperature <= 0.0:
                # already retried at the floor — don't loop forever on a
                # quirk retrying can't fix this time.
                raise RuntimeError(
                    "Model repeatedly attempted a native tool call instead of "
                    "the requested JSON schema, even at temperature=0. This is "
                    "a known openai/gpt-oss-120b quirk on Groq; try rephrasing "
                    "the question more directly."
                ) from e
            # Retry once at a lower temperature, per Groq's own documented
            # mitigation for this exact error.
            return get_next_step(client, transcript, temperature=max(0.0, temperature - 0.2))

        if "max completion tokens reached" in failed_generation:
            # This is NOT transient — it's the same failure family as
            # JSONTruncatedError in Project 1-P-C's groq_client.py: the
            # token cap was too low for this response, and retrying with
            # the SAME cap will truncate at roughly the same point again.
            # Unlike the tool-call quirk above, lowering temperature won't
            # fix this — only a higher cap would, and that's a code change,
            # not something to retry our way out of at runtime.
            raise RuntimeError(
                "Response truncated by max_completion_tokens before producing "
                "valid JSON. This is not a transient error — retrying with the "
                "same token limit will fail the same way. If this recurs, "
                "raise max_completion_tokens further in get_next_step()."
            ) from e

        raise
    content = response.choices[0].message.content
    return AgentStep.model_validate_json(content)


def run_agent(question: str, verbose: bool = True) -> str:
    """Runs the full ReAct loop for one question. Returns the final answer
    text. Prints each Thought/Action/Observation as it happens if verbose,
    so the loop's reasoning is genuinely visible, not just the end result —
    this is what makes 'agent decision logs' real rather than a label."""
    client = get_client()
    transcript = AgentTranscript(question=question)

    for iteration in range(1, MAX_ITERATIONS + 1):
        step = get_next_step(client, transcript)

        if verbose:
            print(f"\n--- Iteration {iteration} ---")
            print(f"Thought: {step.thought}")
            print(f"Action: {step.action}[{step.action_input}]")

        if step.action == "final_answer":
            transcript.steps.append((step, None))
            if verbose:
                print(f"Final Answer: {step.action_input}")
            return step.action_input

        # Repeat-action guard: observed live that the model can re-issue
        # an IDENTICAL action+action_input it already ran (e.g. calling
        # calculate[12*7] twice in a row), instead of recognizing the
        # answer is already in its own transcript. Rather than silently
        # re-running the tool (wasted work, and a second wasted API call
        # next iteration if it keeps happening), detect the exact repeat
        # and feed back a pointed reminder as the observation instead of
        # the tool's real output — this nudges the model to look at its
        # own history rather than just retrying blindly.
        is_repeat = any(
            prev_step.action == step.action and prev_step.action_input == step.action_input
            for prev_step, _ in transcript.steps
        )
        if is_repeat:
            observation = (
                f"You already called {step.action}[{step.action_input}] earlier "
                f"in this conversation — check the Observation above for the "
                f"result instead of repeating the same action."
            )
            if verbose:
                print(f"Observation: {observation} (repeat detected, tool NOT re-run)")
        else:
            observation = run_tool(step.action, step.action_input)
            if verbose:
                print(f"Observation: {observation}")

        transcript.steps.append((step, observation))

    # Loop exhausted without reaching final_answer — fail clearly rather
    # than silently return something misleading.
    raise RuntimeError(
        f"Agent did not reach a final answer within {MAX_ITERATIONS} iterations. "
        f"Last thought was: {transcript.steps[-1][0].thought!r}"
    )